name: unite_kingdoms
description: Medieval strategy game combining tower defense with territory conquest
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_analytics: ^10.7.4
  firebase_crashlytics: ^3.4.8
  google_sign_in: ^6.1.6
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  google_mobile_ads: ^4.0.0
  path_provider: ^2.1.1
  connectivity_plus: ^5.0.2
  package_info_plus: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.7
  test: ^1.24.6

flutter:
  uses-material-design: true
  assets:
    - assets/config/
    - assets/images/
    - assets/audio/